version: '3.8'

services:
  content-service:
    build:
      context: ./content-service
    container_name: content-service
    ports:
      - "8000:8000"
    depends_on:
      - content-db
    env_file:
      - ./content-service/.env  # 환경 변수 파일 지정
    networks:
      - app-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8001:8001"
    depends_on:
      - user-db
    env_file:
      - ./user-service/.env  # 환경 변수 파일 지정
    networks:
      - app-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001

  content-db:
    image: postgres:13
    container_name: content-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      - app-network

  content-test-db:
    image: postgres:13
    container_name: content-test-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
    ports:
      - "5435:5432"
    networks:
      - app-network

  user-db:
    image: postgres:13
    container_name: user-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${USER_POSTGRES_DB}
    ports:
      - "5434:5432"
    networks:
      - app-network

  user-test-db:
    image: postgres:13
    container_name: user-test-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${USER_TEST_POSTGRES_DB}
    ports:
      - "5436:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
